# Use the .NET 6.0 SDK base image
FROM mcr.microsoft.com/dotnet/sdk:6.0

# Install necessary tools and dependencies (git, zstd, wget, and p7zip-full)
RUN apt-get update && \
    apt-get install -y git zstd wget p7zip-full && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
