# Use the .NET 6.0 SDK base image
FROM mcr.microsoft.com/dotnet/sdk:6.0

# Configure Node.js v20 repository
RUN curl -fsSL https://deb.nodesource.com/setup_20.10 | bash

# Install necessary tools and dependencies (git, zstd, wget, jq, and p7zip-full)
RUN apt-get update && \
    apt-get install -y git zstd wget jq p7zip-full nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
