Write-Output ""
Write-Output "   █████╗ ██████╗ ████████╗"
Write-Output " ██╔════╝ ██╔══██╗╚══██╔══╝"
Write-Output " ╚█████╗  ██████╔╝   ██║"
Write-Output "  ╚═══██╗ ██╔═══╝    ██║"
Write-Output " ██████╔╝ ██║        ██║"
Write-Output " ╚═════╝  ╚═╝        ╚═╝"
Write-Output "  Once it hits your lips,"
Write-Output "      it's so good!"
Write-Output ""
